### ISSUE TITLE
Fix caching

### ISSUE THREAD

**Issue by burgerdev** [ilastik/lazyflow#170]
1. [x] All caches should ~~provide the methods defined in interface `OpCache`~~ implement their respective interface properly (partial reason for ilastik/ilastik#807)
    * [x] `OpArrayCache` and parents
    * [x] `OpCompressedCache`
    * [x] `OpValueCache` (cannot be tracked reliably, see [this post](http://stackoverflow.com/a/35645) for example)
    * [x] operators that act like caches (`OpLabelVolume`, `OpFilterLabels`)
    * [x] missing something?
  2. [x] add an additional field "cache info" to `MemInfoNode`
  * [x] `ArrayCacheMemoryManager` should be replaced by `CacheMemoryManager` which
    * [x] should manage ~~named caches~~ all caches that explicitly state that they want to be managed
    * [x] should be started explicitly, not by importing some file (allow non-cache applications to not have a daemon thread for caches)
  * [x] remove deadlock possibilities (#79)
  * [x] fix report generation (#148)
  * [x] ~~fix priority calculation~~ (#173)
  * [x] ~~perhaps remove drtile?~~ (#80) see #181 
  * [x] **extensive testing in ilastik**

**Comment by burgerdev** [comment]
Progress see #160.

**Comment by burgerdev** [comment]
I think this is ready for being tested by other devs...

**Comment by burgerdev** [comment]
PR merged.
